### PR TITLE
Update config.schema.json

### PR DESCRIPTION
**Pull request by donavanbecker**
@arendruni took out headerdisplay and footerdisplay since it is not for this plugin.... Sorry.

### CODE REVIEW

**Comment by arendruni** [comment]
Thank, I was fixing that, but you beat me.
Before merging this PR could you remove the `accessory` property? Since it’s [not necessary](https://github.com/oznu/homebridge-config-ui-x/wiki/Developers:-Plugin-Settings-GUI#basic-structure) to config-ui-x.

**Comment by donavanbecker** [comment]
> @donavanbecker Thank, I was fixing that, but you beat me.
> Before merging this PR could you remove the `accessory` property? Since it’s [not necessary](https://github.com/oznu/homebridge-config-ui-x/wiki/Developers:-Plugin-Settings-GUI#basic-structure) to config-ui-x.

isn't the accessory in your [sample config](https://github.com/arendruni/homebridge-pihole/blob/master/sample-config.json)?

**Comment by arendruni** [comment]
There’s no need to add the `accessory` attribute in the schema object, it will be automatically added based on the `pluginType`.

**Comment by donavanbecker** [comment]
> There’s no need to add the `accessory` attribute in the schema object, it will be automatically added based on the `pluginType`.

Oh okay, didn't know that. Good to know! i have made those changes.

**Pull request merged**
